In [ ]:
from ansys.aedt.core import Desktop, Hfss, Q3d
from pathlib import Path
import traceback
import pandas as pd


desktop = Desktop(version="2025.2", new_desktop=False, student_version=True, port=50051, close_on_exit=False)
q3d = Q3d(project="Project13", new_desktop=False, close_on_exit=False)

PyAEDT INFO: Python version 3.12.12 (main, Oct 31 2025, 23:00:21) [MSC v.1944 64 bit (AMD64)].
PyAEDT INFO: PyAEDT version 0.23.0.
PyAEDT INFO: Initializing new Desktop session.
PyAEDT INFO: Log on console is enabled.
PyAEDT INFO: Log on file C:\Users\abhis\AppData\Local\Temp\pyaedt_abhis_24a04567-50db-4f68-81e9-61ea6aa38c45.log is enabled.
PyAEDT INFO: Log on AEDT is disabled.
PyAEDT INFO: Connecting to AEDT gRPC session on port 50051.
PyAEDT INFO: AEDT installation Path C:\Program Files\ANSYS Inc\ANSYS Student\v252\AnsysEM

In [2]:
q3d.analyze(setup="Setup")

PyAEDT INFO: Project Project13 Saved correctly
PyAEDT INFO: Solving design setup Setup
PyAEDT INFO: Design setup Setup solved correctly in 0.0h 0.0m 3.0s

True

In [39]:
cap_data = q3d.post.get_solution_data(
    expressions=q3d.post.get_all_report_quantities()["Matrix"]["Setup : AdaptivePass"]["C Matrix"],
    context="Original",
    setup_sweep_name="Setup : AdaptivePass",
    variations={"Pass": ["8"]})
pass_c_df = pd.DataFrame([(*k[2:-1].split(','),  v[0, -1])for k, v in cap_data.full_matrix_mag_phase[0].items()], columns=["node1", "node2", "cap"   ]).pivot(index="node1", columns="node2", values="cap").rename_axis(None, axis=1).rename_axis(None, axis=0)
pass_c_df,q3d.units.capacitance

PyAEDT WARNING: No report category provided. Automatically identified Matrix
PyAEDT INFO: Solution Data Correctly Loaded.
Time to initialize solution data:0.01840066909790039
Time to initialize solution data:0.10571789741516113

(                          bus1_connector_pad_Q1  bus2_connector_pad_Q1  \
 bus1_connector_pad_Q1                  0.050666               0.000423
 bus2_connector_pad_Q1                  0.000423               0.054946
 ground_main_plane                      0.034047               0.036350
 pad_bot_Q1                             0.001566               0.014290
 pad_top_Q1                             0.013500               0.001838
 readout_connector_pad_Q1               0.000205               0.001028

                           ground_main_plane  pad_bot_Q1  pad_top_Q1  \
 bus1_connector_pad_Q1              0.034047    0.001566    0.013500
 bus2_connector_pad_Q1              0.036350    0.014290    0.001838
 ground_main_plane                  0.239245    0.031550    0.038192
 pad_bot_Q1                         0.031550    0.099558    0.030711
 pad_top_Q1                         0.038192    0.030711    0.089199
 readout_connector_pad_Q1           0.037190    0.019241    0.002226

                           readout_connector_pad_Q1
 bus1_connector_pad_Q1                     0.000205
 bus2_connector_pad_Q1                     0.001028
 ground_main_plane                         0.037190
 pad_bot_Q1                                0.019241
 pad_top_Q1                                0.002226
 readout_connector_pad_Q1                  0.061007  ,
 'pF')

In [37]:
last_cap_qty_name=  f"cap ({q3d.units.capacitance})"
last_cap_data = q3d.post.get_solution_data(
    expressions=q3d.post.get_all_report_quantities()["Matrix"]["Setup : LastAdaptive"]["C Matrix"],
    context="Original",
    setup_sweep_name="Setup : LastAdaptive",
    variations={"Pass": ["1"]})
last_pass_c_df = pd.DataFrame([(*k[2:-1].split(','),  v[0, -1])for k, v in last_cap_data.full_matrix_mag_phase[0].items()], columns=["node1", "node2", last_cap_qty_name   ]).pivot(index="node1", columns="node2", values=last_cap_qty_name).rename_axis(None, axis=1).rename_axis(None, axis=0)
last_pass_c_df

PyAEDT WARNING: No report category provided. Automatically identified Matrix
PyAEDT INFO: Solution Data Correctly Loaded.
Time to initialize solution data:0.0073757171630859375
Time to initialize solution data:0.09889340400695801

,bus1_connector_pad_Q1,bus2_connector_pad_Q1,ground_main_plane,pad_bot_Q1,pad_top_Q1,readout_connector_pad_Q1
bus1_connector_pad_Q1,0.050666,0.000423,0.034047,0.001566,0.013500,0.000205
bus2_connector_pad_Q1,0.000423,0.054946,0.036350,0.014290,0.001838,0.001028
ground_main_plane,0.034047,0.036350,0.239245,0.031550,0.038192,0.037190
pad_bot_Q1,0.001566,0.014290,0.031550,0.099558,0.030711,0.019241
pad_top_Q1,0.013500,0.001838,0.038192,0.030711,0.089199,0.002226
readout_connector_pad_Q1,0.000205,0.001028,0.037190,0.019241,0.002226,0.061007

In [33]:
cond_qty_name=  f"cond ({q3d.units.conductance})"
cond_data = q3d.post.get_solution_data(
    expressions=q3d.post.get_all_report_quantities()["Matrix"]["Setup : AdaptivePass"]["G Matrix"],
    context="Original",
    setup_sweep_name="Setup : AdaptivePass",
    variations={"Pass": ["8"]})
pass_g_df = pd.DataFrame([(*k[2:-1].split(','),  v[0, -1])for k, v in cond_data.full_matrix_mag_phase[0].items()], columns=["node1", "node2", cond_qty_name  ]).pivot(index="node1", columns="node2", values=cond_qty_name).rename_axis(None, axis=1).rename_axis(None, axis=0)
pass_g_df

PyAEDT WARNING: No report category provided. Automatically identified Matrix
PyAEDT INFO: Solution Data Correctly Loaded.
Time to initialize solution data:0.009639739990234375
Time to initialize solution data:0.14787554740905762

,bus1_connector_pad_Q1,bus2_connector_pad_Q1,ground_main_plane,pad_bot_Q1,pad_top_Q1,readout_connector_pad_Q1
bus1_connector_pad_Q1,0.0,0.0,0.0,0.0,0.0,0.0
bus2_connector_pad_Q1,0.0,0.0,0.0,0.0,0.0,0.0
ground_main_plane,0.0,0.0,0.0,0.0,0.0,0.0
pad_bot_Q1,0.0,0.0,0.0,0.0,0.0,0.0
pad_top_Q1,0.0,0.0,0.0,0.0,0.0,0.0
readout_connector_pad_Q1,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
q3d.post.get_all_report_quantities()["Matrix"]["Setup : AdaptivePass"]["G Matrix"]

['G(bus1_connector_pad_Q1,bus1_connector_pad_Q1)',
 'G(bus1_connector_pad_Q1,bus2_connector_pad_Q1)',
 'G(bus1_connector_pad_Q1,ground_main_plane)',
 'G(bus1_connector_pad_Q1,pad_bot_Q1)',
 'G(bus1_connector_pad_Q1,pad_top_Q1)',
 'G(bus1_connector_pad_Q1,readout_connector_pad_Q1)',
 'G(bus2_connector_pad_Q1,bus1_connector_pad_Q1)',
 'G(bus2_connector_pad_Q1,bus2_connector_pad_Q1)',
 'G(bus2_connector_pad_Q1,ground_main_plane)',
 'G(bus2_connector_pad_Q1,pad_bot_Q1)',
 'G(bus2_connector_pad_Q1,pad_top_Q1)',
 'G(bus2_connector_pad_Q1,readout_connector_pad_Q1)',
 'G(ground_main_plane,bus1_connector_pad_Q1)',
 'G(ground_main_plane,bus2_connector_pad_Q1)',
 'G(ground_main_plane,ground_main_plane)',
 'G(ground_main_plane,pad_bot_Q1)',
 'G(ground_main_plane,pad_top_Q1)',
 'G(ground_main_plane,readout_connector_pad_Q1)',
 'G(pad_bot_Q1,bus1_connector_pad_Q1)',
 'G(pad_bot_Q1,bus2_connector_pad_Q1)',
 'G(pad_bot_Q1,ground_main_plane)',
 'G(pad_bot_Q1,pad_bot_Q1)',
 'G(pad_bot_Q1,pad_top_Q1)',
 'G(pad_bot_Q1,readout_connector_pad_Q1)',
 'G(pad_top_Q1,bus1_connector_pad_Q1)',
 'G(pad_top_Q1,bus2_connector_pad_Q1)',
 'G(pad_top_Q1,ground_main_plane)',
 'G(pad_top_Q1,pad_bot_Q1)',
 'G(pad_top_Q1,pad_top_Q1)',
 'G(pad_top_Q1,readout_connector_pad_Q1)',
 'G(readout_connector_pad_Q1,bus1_connector_pad_Q1)',
 'G(readout_connector_pad_Q1,bus2_connector_pad_Q1)',
 'G(readout_connector_pad_Q1,ground_main_plane)',
 'G(readout_connector_pad_Q1,pad_bot_Q1)',
 'G(readout_connector_pad_Q1,pad_top_Q1)',
 'G(readout_connector_pad_Q1,readout_connector_pad_Q1)']

In [20]:
q3d.cleanup_solution()

True

In [2]:
desktop.release_desktop(close_projects=False, close_on_exit=False)

PyAEDT INFO: Desktop has been released.

True